apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: kf-nb-controller-sm
  namespace: redhat-ods-monitoring
spec:
  namespaceSelector:
    matchNames:
      - redhat-ods-applications
  endpoints:
    - relabelings:
      - action: keep
        regex: ^(notebook-controller-service)$
        sourceLabels:
          - __meta_kubernetes_service_name
        targetLabel: kubernetes_name
      - action: replace
        regex: '(.+):(\d+)'
        replacement: '${1}:8080'
        sourceLabels:
          - __address__
        targetLabel: __address__
      scheme: http
      honorLabels: true
      path: /metrics