apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: odh-model-controller-controller-sm
  labels:
    rhoai-monitoring: 'true'
  namespace: redhat-ods-monitoring
spec:
  namespaceSelector:
    matchNames:
      - redhat-ods-applications
  endpoints:
    - action: keep
      regex: ^(odh-model-controller-metrics-service)$
      sourceLabels:
        - __meta_kubernetes_service_name
      targetLabel: kubernetes_name
    - action: replace
      regex: '(.+):(\d+)'
      replacement: '${1}:8080'
      sourceLabels:
        - __address__
      targetLabel: __address__
      scheme: http
      honorLabels: true