apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    rhoai-monitoring: 'true'
  name: rhoai-metrics-sc
  namespace: redhat-ods-monitoring
spec:
  scheme: HTTP
  honorLabels: true
  kubernetesSDConfigs:
    - namespaces:
        names:
          - redhat-ods-operator
      role: pod
  metricsPath: /metrics
  relabelings:
    - action: keep
      regex: ^(true)$
      sourceLabels:
        - __meta_kubernetes_pod_labelpresent_control_plane
      targetLabel: kubernetes_name
    - action: replace
      regex: '(.*)'
      replacement: '${1}:8080'
      sourceLabels:
        - __address__
      targetLabel: __address__
