apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: data-science-pipelines-operator-alerting-rules
  labels:
    rhoai-monitoring: 'true'
  namespace: redhat-ods-monitoring
spec:
  groups:
    - name: SLOs - Data Science Pipelines Operator
      rules:
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[1d])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate1d
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[1h])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate1h
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[2h])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate2h
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[30m])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate30m
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[3d])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate3d
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[5m])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate5m
      - expr: |
          1 - avg_over_time(probe_success{instance=~"data-science-pipelines-operator-.*", job="user_facing_endpoints_status_dsp"}[6h])
        labels:
          instance: data-science-pipelines-operator
        record: probe_success:burnrate6h

    - name: SLOs - Data Science Pipelines Application
      rules:
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[1d])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[1d])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate1d
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[1h])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[1h])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate1h
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[2h])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[2h])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate2h
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[30m])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[30m])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate30m
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[3d])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[3d])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate3d
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[5m])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[5m])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate5m
      - expr: |
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*",code=~"5.."}[6h])) by (exported_namespace)
          /
          sum(rate(haproxy_backend_http_responses_total{route=~"ds-pipeline-.*"}[6h])) by (exported_namespace)
        labels:
          component: dsp
        record: haproxy_backend_http_responses_total:burnrate6h