apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kserve-recording-rules
  labels:
    rhoai-monitoring: 'true'
  namespace: redhat-ods-monitoring
spec:
  groups:
    - name: SLOs - Kserve Controller Manager
      rules:
      - expr: |
          absent(up{job=~'Kserve Controller Manager'}) * 0 or vector(1)
        labels:
          instance: kserve-controller-manager
        record: probe_success
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[1d]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate1d
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[1h]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate1h
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[2h]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate2h
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[30m]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate30m
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[3d]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate3d
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[5m]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate5m
      - expr: |
          1 - min(avg_over_time(probe_success{instance="kserve-controller-manager"}[6h]))
        labels:
          instance: kserve-controller-manager
        record: probe_success:burnrate6h