apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: model-mesh-alerting-rules
  labels:
    rhoai-monitoring: 'true'
  namespace: redhat-ods-monitoring
spec:
  groups:
    - name: SLOs-probe_success_modelmesh
      rules:
      - alert: Modelmesh Controller Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.instance }} (current value: {{ $value }}).'
          triage: "https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/blob/main/RHODS/Model-Serving/rhods-modelmesh-controller-probe-success-burn-rate.md"
          summary: Modelmesh Controller Probe Success Burn Rate
        expr: |
          sum(probe_success:burnrate5m{instance=~"modelmesh-controller"}) by (instance) > (14.40 * (1-0.98000))
          and
          sum(probe_success:burnrate1h{instance=~"modelmesh-controller"}) by (instance) > (14.40 * (1-0.98000))
        for: 2m
        labels:
          severity: critical
          namespace: redhat-ods-applications
      - alert: Modelmesh Controller Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.instance }} (current value: {{ $value }}).'
          triage: "https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/blob/main/RHODS/Model-Serving/rhods-modelmesh-controller-probe-success-burn-rate.md"
          summary: Modelmesh Controller Probe Success Burn Rate
        expr: |
          sum(probe_success:burnrate30m{instance=~"modelmesh-controller"}) by (instance) > (6.00 * (1-0.98000))
          and
          sum(probe_success:burnrate6h{instance=~"modelmesh-controller"}) by (instance) > (6.00 * (1-0.98000))
        for: 15m
        labels:
          severity: critical
          namespace: redhat-ods-applications
      - alert: Modelmesh Controller Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.instance }} (current value: {{ $value }}).'
          triage: "https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/blob/main/RHODS/Model-Serving/rhods-modelmesh-controller-probe-success-burn-rate.md"
          summary: Modelmesh Controller Probe Success Burn Rate
        expr: |
          sum(probe_success:burnrate2h{instance=~"modelmesh-controller"}) by (instance) > (3.00 * (1-0.98000))
          and
          sum(probe_success:burnrate1d{instance=~"modelmesh-controller"}) by (instance) > (3.00 * (1-0.98000))
        for: 1h
        labels:
          severity: warning
          namespace: redhat-ods-applications