apiVersion: monitoring.rhobs/v1
kind: PodMonitor
metadata:
  name: kserve-controller-manager-sm
  labels:
    rhoai-monitoring: 'true'
  namespace: redhat-ods-monitoring
spec:
  podMetricsEndpoints:
    - scheme: http
      honorLabels: true
      relabelings:
        - action: keep
          regex: ^(kserve-controller-manager)$
          sourceLabels:
            - __meta_kubernetes_pod_label_control_plane
          targetLabel: kubernetes_name
        - action: replace
          regex: '(.+):(\d+)'
          replacement: '${1}:8080'
          sourceLabels:
            - __address__
          targetLabel: __address__
  namespaceSelector:
    matchNames:
      - redhat-ods-applications
  selector:
    matchExpressions:
      - values:
          - kserve
        key: app.kubernetes.io/part-of
        operator: In
