apiVersion: monitoring.rhobs/v1
kind: PodMonitor
metadata:
  name: rhoai-metrics-pm
  labels:
    rhoai-monitoring: 'true'
  namespace: redhat-ods-monitoring
spec:
  podMetricsEndpoints:
    - scheme: http
      honorLabels: true
      relabelings:
        - action: keep
          regex: ^(true)$
          sourceLabels:
            - __meta_kubernetes_pod_labelpresent_control_plane
          targetLabel: kubernetes_name
        - action: replace
          regex: '(.*)'
          replacement: '${1}:8080'
          sourceLabels:
            - __address__
          targetLabel: __address__
  namespaceSelector:
    matchNames:
      - redhat-ods-operator
  selector:
    matchExpressions:
      - values:
          - rhods-operator
        key: name
        operator: In
